name: Deploy to VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:


env:
  VPS_USER: ${{ secrets.VPS_USER }}
  VPS_IP: ${{ secrets.VPS_IP }}
  VPS_PORT: ${{ secrets.VPS_PORT }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy on VPS
        run: |
          ssh -o StrictHostKeyChecking=no -p $VPS_PORT $VPS_USER@$VPS_IP << 'EOF'
            cd /home/user-deploy/apps/room2remember-app
            git pull origin main
            docker stop room2remember-container || true
            docker rm room2remember-container || true
            docker rmi room2remember-image
            docker build -t room2remember-image .
            docker run -d --name room2remember-container -p 4020:80 room2remember-image
          EOF
